services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    # Descomentar para entornos de desarrollo con hot reload
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://backend:3000/api  # Si necesitas conectar con un backend
